<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <parent>
        <groupId>com.activity-master</groupId>
        <artifactId>activitymaster-group</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>wallet-master</artifactId>
    <packaging>jar</packaging>
    <name>Wallet Master</name>

    <properties>
        <project.scm.nameUrl>/Activity-Master/WalletMaster</project.scm.nameUrl>
    </properties>
	
    <dependencies>
        <dependency>
            <groupId>com.activity-master</groupId>
            <artifactId>activity-master</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.guicedee.modules.services</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.activity-master</groupId>
            <artifactId>activity-master</artifactId>
            <type>test-jar</type>
            <version>${project.version}</version>
            <classifier>tests</classifier>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-reads org.jboss.logging=org.hibernate.reactive
                        --add-reads org.hibernate.orm.core=com.guicedee.activitymaster.fsdm
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
